---
apiVersion: v1
kind: ConfigMap
metadata:
  name: java-spiffe-helper
data:
  java-spiffe-helper.properties: |
    keyStorePath=/certs/keystore.p12
    keyStorePass=password
    keyPass=password
    trustStorePath=/certs/truststore.p12
    trustStorePass=password
    keyStoreType=pkcs12
    keyAlias=spiffe
    spiffeSocketPath=unix:/run/spire/agent-sockets/spire-agent.sock
